stages:
  data_ingestion:
    cmd: python src/wildblueberry/pipeline/stage_01_data_ingestion.py
    deps:
      - src/wildblueberry/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv

  data_validation:
    cmd: python src/wildblueberry/pipeline/stage_02_data_validation.py
    deps:
      - src/wildblueberry/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv
    outs:
      - artifacts/data_validation/status.txt
      
  data_transformation:
    cmd: python src/wildblueberry/pipeline/stage_03_data_transformation.py
    deps:
      - src/wildblueberry/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
      # - artifacts/data_transformation/categorical.json
  
  model_trainer:
    cmd: python src/wildblueberry/pipeline/stage_04_model_trainer.py
    deps:
      - src/wildblueberry/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_trainer/model.joblib
      

      
  model_evaluation:
    cmd: python src/wildblueberry/pipeline/stage_05_model_evaluation.py
    deps:
      - src/wildblueberry/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/model_trainer/model.joblib
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_evaluation/metrics.json
