artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/competitions/wild-blueberry-yield-prediction-challenge/data
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/train.csv


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/train.csv
  categorical_feature_path : categorical.joblib
  categorical_json_path : categorical.json

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  train_data_path: artifacts/data_transformation/train.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: https://dagshub.com/SunilKumar-ugra/Wild-blueberry-yeild-prediction.mlflow
